"""add monthly field to user

Revision ID: ebed079772af
Revises: 73c4380fcc05
Create Date: 2022-05-15 13:16:09.307975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ebed079772af"
down_revision = "73c4380fcc05"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stats", sa.Column("last_monthly", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stats", "last_monthly")
    # ### end Alembic commands ###
